#!/bin/sh

#cd /home/okusako/prog/carmen/carmen.0.4.6.i/bin
#cd /usr/local/carmen_new/bin

xterm -bg white  -geometry 75x10+0+0   &
xterm -bg white  -geometry 75x10+0+180 &
xterm -bg white  -geometry 75x10+0+360 &
xterm -bg white  -geometry 75x10+0+540 &

#if [ $# -ne 0 ]
#then
    xterm -bg white -geometry 75x10+555+540 &
    xterm -bg white -geometry 75x10+555+360 &
    xterm -bg white -geometry 75x10+555+180 &
#fi

