OBJS= smmap.o scanmatcher.o scanmatcherprocessor.o 
APPS= scanmatch_test 

LDFLAGS+= -lutils -lsensor_range -llog
CPPFLAGS+=-I../sensor

-include ../global.mk
-include ../build_tools/Makefile.generic-shared-object

